 #+TITLE: journal 2020
#+DATE: 2020-01-19
#+STARTUP: content
#+OPTIONS: toc:t H:2 num:nil

* Monday, 20 January 2020
** 08:07 晨间记录
*** 天气/温度/地点：雾/0°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨晚睡前在京东上买了精酿啤酒，价格130多。听大内一直对精酿啤酒很好奇，这次恰逢春节，终于有机会品尝一下了。
    12:30熄灯睡觉，估计要到1:00多才睡着。6点和7点分别醒来了一次，小眯了一会就到了8点。又记不清梦见什么了。我应该在早晨记忆尚存的时候做些记录。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期目标：有能力和时间带父母环游世界；工作上有引以为傲的作品；个人方面更自律，多读书，更优秀。
    短期目标：考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    吃完早饭，到超市买东西（读书笔记相关，口罩...），然后今天的主要工作也是总结完《搞定》，调整org-agenda。顺带读一读《傅雷家书》。
    * [X] 买东西
    * [X] 总结搞定
    * [X] 阅读《傅雷家书》

** 21:31 晚间总结
*** 几句话总结一下今天？
    早上在小吃铺吃了馄饨和烧卖，然后去万达的超市逛了逛，买了部分做读书笔记的文具。中午睡了会，下午总结搞定，折腾了blog。晚上读了会《傅雷家书》。
*** 今天有什么值得夸奖自己的地方？（鼓励）
    明白了一个道理：这个世界上令我好奇的事物，我想学习的知识，我想阅读的书籍浩如烟海，穷尽一生我也不能全部了解，学习，读完。从这个意义上看，生命短暂，时间宝贵，且行且珍惜。

开心的是通过《但是还有书籍》这部纪录片，让我认识了B站的up主小隐，从而让我意识到b站有很丰富的资源，很多有意思的up主的视频，很多前人的经验。它就像一个知识宝库，你的好奇心越大，探索欲越强烈，它带给你的智慧也越多。感谢，感恩有这样优秀的平台。也很幸运我认识到了这个道理。
*** 今天有什么待改进的地方？（反思）
    关于ZW这件事情，我一直没有认真的讨论过它。好吧，我实在是说服不了自己，的确的全方面的好好了解一下它。目前姑且制定一个习惯周期，这是比较合理的。把这个习惯记录进blog，表明我对它的重视。

关于中午午休。首要问题是午休前刷手机过了午休时间，进而影响下午的学习安排；其次是午休时间到了仍然瞌睡，不能果断起床。主要就是这两个问题。
之前一直想培养在床上不玩手机的习惯，多次失败后没有坚持下来，便不了了之了。现在我想将这个习惯的培养提上日程了。它会是解决午休第一个问题的灵丹妙药。至于第二个问题，根源在睡眠质量不高。所以平时要多锻炼，少ZW。减少从醒来的状态切换到学习的状态的时间也是很好的解决办法。这就需要改变午休的方式，比如在书房睡觉。先待定吧，着重把第一个问题解决好。

关于文字表达。写上面这段文字让我意识到自己缺乏书面表达的训练。如果我不动脑子的书写，文字中便充满了语病。如果我有意识的注重书写时的逻辑表达和用词，语句便会通顺许多。所以以后切忌“意识流式”写作，多留意表达通顺，多训练表达的美感。

还有一些，明天接着反思。

*** 还有什么想说的？（感悟）
    我不必为没有履行对自己的承诺而烦心，既然时间已经过去，何不乐观的去反思。每天不能只有反思，也要学会找到自己做得好的地方，懂得感恩。我把人的精神状态比作一个天秤，左边是鼓励，右边是反思。任何一边偏重都会导致天秤失衡。

读《傅雷家书》，在傅雷给儿子傅聪的信中，我可以真切的感受到傅雷对儿子生活方方面面的关心，这些内容关于俄文学习，关于乐理学习，关于处理恋爱与艺术的关系，关于儿子的心情....也有对自己的反思，傅雷的脾气有的时候会让儿子、妻子忧心。不行了，我得多读别人的文字，写的太不流畅了！
* Sunday, 19 January 2020
** 09:49 晨间日记
*** 天气/温度/地点：晴/4°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨天12:40多睡觉，记不清梦见了什么。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期愿景：有能力随时带父母环游世界；计算机行业里作出自己的成绩；个人方面养成自律的习惯并能影响他人。目前的目标是考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    今天做重要的事情是搞定org agenda。

*** 几句话总结一下今天？
    上午整理《搞定》笔记，中午吃了蛋炒饭，看完了《但是还有书籍》，了解了B站的up主小隐。下午睡了一觉，跑步30min，3.5km。晚上折腾blog，将org-journal导出到blog。晚上洗了澡，回来买了份“章福元”吃。
*** 今天最大的收获是什么？（鼓励）
    看了小隐一期关于做读书笔记的视频，了解了读书的仪式感：布置一个优雅的环境，用一些小道具，冲一杯热咖啡...
*** 有什么有待改进的地方？（反思）
    我感觉自己又陷入了那个怪圈：一旦一开始没有做好，接下来就会全盘皆输。早上没有按照预期的时间起床，接下来一天的时间就荒废了。这是一种很不好的做法。破局的办法是培养一些好的习惯，像晨间日记一样。习惯就是那些即使一天的状况再再糟糕，也要能雷打不动去做事情。培养了这些好的习惯（无论是长期的还是短期的），起码能保证自己的心情不那么糟糕。

    举几个例子：不知道要做什么的时候，看书！早上起来出去慢跑个几公里（前提是起早点）！傍晚按时跑步！中午不要在床上睡觉！
    另一个方面，我得认识到这几天糟糕的情绪与状态的根源：没有兑现自己的承诺。每天我都在晨间日记里面写下今天要做的事情，但是当自己没有履行承诺时，便会产生消极情绪。这种消极情绪持续积累便让人忘了GTD。所有以后我每天只列出一件最重要的事情，其余的培养成习惯，剩下的做一步看一步。我不知道这么做是否合理，但对我来说是有效的。
** 15:00 看完《但是还有书籍》有感
   看完《但是还有书籍》和小隐的一期视频后，我有一种深深的焦虑感。焦虑于我没能在自己前20年的人生里与阅读为伴，没能在阅读的世界里开拓眼界，汲取知识，培养素养，学会表达。如果我能像小隐一样5岁便能在书籍的海洋中遨游，在知识的圣殿里流连忘返，此刻的我一定不会是此刻的我。我的心境，我的思考方式，对待生活的态度，我的人生观、价值观都会有很大的不同。这个世界没有如果，幸好我遇见阅读还不算太晚。

始终让我意难平的是小隐的手账视频介绍自己在英国游学的经历。这种带着朝圣的心境在他国参观，享受自然最纯粹的洗涤，异国他乡的求学的心境与情结在我的脑海中挥之不去。我向往这样的生活。可能，当我到了那个环境时就没了此番的憧憬，但此刻的心情实在是令人难以平复。总结就是在面对优秀的人时，内心会产生愧疚感。对平时自己浪费了很多的时间而后悔。
