 #+TITLE: journal 2020
#+DATE: 2020-01-19
#+STARTUP: content
#+OPTIONS: toc:t H:2 num:nil

* Sunday, 19 January 2020
** 09:49 晨间日记
*** 天气/温度/地点：晴/4°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨天12:40多睡觉，记不清梦见了什么。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期愿景：有能力随时带父母环游世界；计算机行业里作出自己的成绩；个人方面养成自律的习惯并能影响他人。目前的目标是考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    今天做重要的事情是搞定org agenda。

*** 几句话总结一下今天？
    上午整理《搞定》笔记，中午吃了蛋炒饭，看完了《但是还有书籍》，了解了B站的up主小隐。下午睡了一觉，跑步30min，3.5km。晚上折腾blog，将org-journal导出到blog。晚上洗了澡，回来买了份“章福元”吃。
*** 今天最大的收获是什么？（鼓励）
    看了小隐一期关于做读书笔记的视频，了解了读书的仪式感：布置一个优雅的环境，用一些小道具，冲一杯热咖啡...
*** 有什么有待改进的地方？（反思）
    我感觉自己又陷入了那个怪圈：一旦一开始没有做好，接下来就会全盘皆输。早上没有按照预期的时间起床，接下来一天的时间就荒废了。这是一种很不好的做法。破局的办法是培养一些好的习惯，像晨间日记一样。习惯就是那些即使一天的状况再再糟糕，也要能雷打不动去做事情。培养了这些好的习惯（无论是长期的还是短期的），起码能保证自己的心情不那么糟糕。

    举几个例子：不知道要做什么的时候，看书！早上起来出去慢跑个几公里（前提是起早点）！傍晚按时跑步！中午不要在床上睡觉！
    另一个方面，我得认识到这几天糟糕的情绪与状态的根源：没有兑现自己的承诺。每天我都在晨间日记里面写下今天要做的事情，但是当自己没有履行承诺时，便会产生消极情绪。这种消极情绪持续积累便让人忘了GTD。所有以后我每天只列出一件最重要的事情，其余的培养成习惯，剩下的做一步看一步。我不知道这么做是否合理，但对我来说是有效的。
** 15:00 看完《但是还有书籍》有感
   看完《但是还有书籍》和小隐的一期视频后，我有一种深深的焦虑感。焦虑于我没能在自己前20年的人生里与阅读为伴，没能在阅读的世界里开拓眼界，汲取知识，培养素养，学会表达。如果我能像小隐一样5岁便能在书籍的海洋中遨游，在知识的圣殿里流连忘返，此刻的我一定不会是此刻的我。我的心境，我的思考方式，对待生活的态度，我的人生观、价值观都会有很大的不同。这个世界没有如果，幸好我遇见阅读还不算太晚。

始终让我意难平的是小隐的手账视频介绍自己在英国游学的经历。这种带着朝圣的心境在他国参观，享受自然最纯粹的洗涤，异国他乡的求学的心境与情结在我的脑海中挥之不去。我向往这样的生活。可能，当我到了那个环境时就没了此番的憧憬，但此刻的心情实在是令人难以平复。总结就是在面对优秀的人时，内心会产生愧疚感。对平时自己浪费了很多的时间而后悔。
