#+TITLE: journal 2020
#+DATE: 2020-01-19
#+STARTUP: content
#+OPTIONS: toc:t H:1 num:0

#+begin_quote
生活就是写一本书，我想用真实的，诗意的笔触记录下点滴的回忆!
#+end_quote

* Sunday, 19 January 2020
** 09:49 晨间日记
*** 天气/温度/地点：晴/4°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨天12:40多睡觉，记不清梦见了什么。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期愿景：有能力随时带父母环游世界；计算机行业里作出自己的成绩；个人方面养成自律的习惯并能影响他人。目前的目标是考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    今天做重要的事情是搞定org agenda。

*** 几句话总结一下今天？
    将每天的journal记录在博客里，修改了orgh-journal的流程和模版。
*** 今天最大的收获是什么？（鼓励）
*** 有什么有待改进的地方？（反思）
    我感觉自己又陷入了那个怪圈：一旦一开始没有做好，接下来就会全盘皆输。早上没有按照预期的时间起床，接下来一天的时间就荒废了。这是一种很不好的做法。破局的办法是培养一些好的习惯，像晨间日记一样。习惯就是那些即使一天的状况再再糟糕，也要能雷打不动去做事情。培养了这些好的习惯（无论是长期的还是短期的），起码能保证自己的心情不那么糟糕。

    举几个例子：不知道要做什么的时候，看书！早上起来出去慢跑个几公里（前提是起早点）！傍晚按时跑步！中午不要在床上睡觉！
    另一个方面，我得认识到这几天糟糕的情绪与状态的根源：没有兑现自己的承诺。每天我都在晨间日记里面写下今天要做的事情，但是当自己没有旅行社承诺时，便会产生消极情绪。这种消极情绪持续积累便让人忘了GTD。所有以后我每天只列出一件最重要的事情，其余的培养成习惯，剩下的做一步看一步。我不知道这么做是否合理，但对我来说是有效的。
** 15:00 看完《但是还有书籍》有感

看完《但是还有书籍》和小隐的一期视频后，我有一种深深的焦虑感。焦虑于我没能在自己前20年的人生里与阅读为伴，没能在阅读的世界里开拓眼界，汲取知识，培养素养，学会表达。如果我能像小隐一样5岁便能在书籍的海洋中遨游，在知识的圣殿里流连忘返，此刻的我一定不会是此刻的我。我的心境，我的思考方式，对待生活的态度，我的人生观、价值观都会有很大的不同。这个世界没有如果，幸好我遇见阅读还不算太晚。

始终让我意难平的是小隐的手账视频介绍自己在英国游学的经历。这种带着朝圣的心境在他国参观，享受自然最纯粹的洗涤，异国他乡的求学的心境与情结在我的脑海中挥之不去。我向往这样的生活。可能，当我到了那个环境时就没了此番的憧憬，但此刻的心情实在是令人难以平复。总结就是在面对优秀的人时，内心会产生愧疚感。对平时自己浪费了很多的时间而后悔。

* Saturday, 18 January 2020
** 11:56 晨间日记
*** 天气/温度/地点：晴/4°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨晚12点左右睡觉。可能是看了《灵魂摆渡》中摆渡人背着冥王交易的情节，我也做了一个“无视权威”的梦。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期目标是有能力随时带父母环游世界。个人方面，希望在计算机行业作出自己的成就。个人素质，希望严格自律，并将这种理念与方法带给更多的人。
    目前短期的目标是考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    搞完org-agenda，跑步，洗澡。然后按照org-agenda行事。

*** 几句话总结一下今天？
    爸妈不在家，也没怎么学习。
*** 今天最大的收获是什么？（鼓励）
    看了一集《但是还有书籍》，讲绘本，爱了。
*** 有什么有待改进的地方？（反思）
    早上因为意识到爸妈回家了，就干脆睡到了11多。要知道我的自律不是做给别人看的。我还是没有意识到早起的重要性。我得把它当作一个习惯来着重培养。

*** 有什么想提醒明天的自己的？
    一日之计在于晨，早点起床。
** 20:12 
   需要思考的几个问题：
   * 项目如何处理？
   * 需要的几个清单？
     日程表(有时间戳)，收集箱，下一步行动（next），将来/也许，等待（waitting），项目。
   * 需要那些情境？
     情境用标签表示：@outside @review @phone
* Friday, 17 January 2020
** 08:39 晨间日记
*** 天气/温度/地点：多云/1°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨晚1点左右睡觉，因为下午睡了很长时间睡不着。做了一个很甜的梦，一心为了爱的人很纯很甜的恋爱，这种感觉真好。
*** 我的人生目标是什么？（长期短期，不同方面）
    随时有能力带父母环游世界，专业上有自己的作品，自律，做更优秀的，并影响他人。
*** 今天打算怎么安排？（上午，下午，晚上）
    上午当然是先看一集《但是还有书籍》，剩下的时间实现org agenda。一定要记住的是中午得午休，不能再看电视剧或其他的事情打断自己的计划。下午先看40min的C++书籍。接着继续搞org agenda。晚上至少要学习1个小时，然后才能和老妈看剧。跑步跑30min，跑完去洗澡。

*** 几句话总结一下今天？
    上午看了一集《但是还有书籍》，然后陪老妈到万达买东西。中午睡了一觉，下午3点起床。然后整理《搞定》。4点多跑步30min，3.4km。晚上看《灵魂摆渡》。
*** 今天最大的收获是什么？（鼓励）
    中午睡了午觉，也起来了，但是玩了一个小时。
*** 有什么有待改进的地方？（反思）
    这几天时间的利用率很低。主要是杂七杂八的事情，也没有必要避免。解决的办法是早上早点起床，下午按时开始学习。

*** 有什么想提醒明天的自己的？
    早上7点起床。
