 #+TITLE: journal 2020
#+DATE: 2020-01-19
#+STARTUP: content
#+OPTIONS: toc:t H:2 num:nil

* Monday, 27 January 2020
** 07:36 晨间记录
*** 天气/温度/地点：多云/2°/上河老家
*** 早上好，昨晚睡得怎么样？
    睡前看了40分钟《傅雷家书》，11:30左右入睡。尝试裸睡，但半夜要起来小便，便穿起了衣服。又梦到了甜甜的恋爱，真好！
*** 当前在培养的习惯是？
    跑步和睡前阅读。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期：有能力带父母随时环游世界；工作上有自己的作品；个人自律。
    短期：考上研究生
*** 今天打算怎么安排？（上午，下午，晚上）
    搞定org agenda，写用org mode搭建blog的的博客，阅读。
** 11:49 org-agenda设计续续
   需要思考的几个问题：
   * 项目如何处理？
   * 需要的几个清单？
     日程表(有时间戳)，收集箱，下一步行动（next），将来/也许，等待（waitting），项目。
   * 需要那些情境？
     情境用标签表示：@outside @review（阅读回顾清单） @phone

GTD的概念和org agenda概念对应
 * 收集箱：#+CATEGORY:Inbox
 * 下一步行动：NEXT关键词
 * 将来/也许：#+CATEGORY:Someday/Maybe
 * 等待清单：WAITTING关键字
 * 项目：@Project
 * 普通任务：TODO

重要的不是GTD的概念与org agenda概念的对应是否合理，重要的是写elisp函数封装处理的细节。
本质上，任务在三块区域迁移：收集箱（未处理），将来/也许清单（预处理），目前要做的工作（即将执行）。
所以建立三个文件：inbox.org（待处理的提示信息），someday.org（将来做的任务和未激活的项目），newgtd.org(单独的任务和已确定下一步行动的活跃项目)

我的几种情境分类：
 * 阅读、回顾相关文章资料 @review
 * 打电话处理相关事务 @phone
 * 需要用到电脑 @computer
 * 思考、研究一些问题并查阅资料 @research

我的几个TODO状态关键词：TODO，NEXT，APPT，WAITTING，DONE，CANCELLED

任务按照内容的分类：goods to buy，books to read, film/episode to watch
** 12:26 头脑风暴
   * buy something
     * 录音设备（声卡，麦克风，耳机）
     * Mac mini
   * 考研复习计划
   * 阅读和做读书笔记的方法与流程
   * 学习elisp和精进计划
   * 学习C++，python，锻炼程序设计能力
   * 学习算法，提高应用能力
   * 跑步减肥，对身体情况不满
   * 规律ZW
   * 记账，leadger的矫正和规范，简化流程，写elisp函数？
   * 让更多的人看到我的blog
   * 博客撰写
     * org mode实现GTD
     * org mode实现blog
   * 每周总结，每月规划，结合子弹笔记。
   * 规范化我的emacs配置
   * 提升英语书面表达，口语能力，单词（项目）
   * 为emacs在国内推广做贡献，录视频，博客文章分享等。
   * 由于拆迁，录老家的视频
   * 我的档案在哪儿？
   * 想做的事情放到someday/maybe，每周从中选出部分准备在本周内执行（单独清单），周末未完成的放回someday/maybe，重新选择。
   * 写任务处理workflow的函数，封装处理细节。
   * 多喝水，早起一杯温水
   * 锻炼，跑步
   * 多阅读，多思考，记录思考
   * 锻炼文字表达，规范总结语言，不啰嗦，不说大白话。
   * 能够在我懈怠时激励鼓舞我的文字，视频等
   * 时常需要浏览启发我的网站，视频等。
   * 情绪日记？为什么要记录？发现更多这样的有益处的习惯。
   * 下一步行动一定要具体可行！！！
   * 打造自己满意的学习办公环境
   * 简化博客处理的流程，傻瓜式的。写到博客里。
** 21:48 晚间总结
*** 今天做了些什么？
    早晨醒来阅读《傅雷家书》40min，中午睡了一觉，晚上去外婆家吃饭。晚上回来折腾org agenda，前进了一大步，真是费脑子!
*** 今天有什么值得夸奖自己的地方？（鼓励）
    org agenda的设计前进了一大步。
*** 今天有什么待改进的地方？（反思）无
*** 还有什么想说的？(感悟) 
    设计org agenda让我感受到了脑细胞新陈代谢的感觉，过度用脑是真的累呀。
    给阅读一本书定一个期限，比如说一周读一本，更有计划。
* Sunday, 26 January 2020
** 08:59 晨间记录
*** 天气/温度/地点：多云/5°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨晚1点多睡。
*** 当前在培养的习惯是？
    跑步和睡前阅读30min
*** 我的人生目标是什么？（长期短期，不同方面）
    长期：有能力带父母随时环游世界；工作上有自己的作品；个人自律。
    短期：考上研究生
*** 今天打算怎么安排？（上午，下午，晚上）
    随缘～
** 21:48 晚间总结
*** 今天做了些什么？
    上午回老家，中午在外婆家吃饭。下午睡了很长时间，晚上搞搞电脑。
*** 今天有什么值得夸奖自己的地方？（鼓励）无
*** 今天有什么待改进的地方？（反思）
    疫情当前，我原本的期望是待在家里，不参加一切的拜年与聚餐。可是早上老爸老妈还要要到外婆家拜年吃饭，我有点不开心，便迟迟不肯起床。应该还是要提前沟通好这些问题。不要被自己的情绪裹挟导致说话做事显得幼稚。
*** 还有什么想说的？(感悟)
“道阻且长，行则将至”，自律是一个漫长且煎熬的过程。这个过程中会有信心满满、动力十足的时刻，也会有怀疑懒惰、萎靡懈怠的念头。后者常常成为我不能持之以恒做一件事情的原因。经历过一次的失败后，我会对自己更狠，要求更严格，可是换来的却是更大的失望。一次两次，往复循环。于是我要思考，问题出在哪？如果想不清楚这个问题，作多少次的努力都是白费！

我找到了答案。问题出在我对待失败的心态。我总是努力避免失败，一旦失败，便会内心难受，这在无形中形成了压力。压力积累，人就会像高压锅一样泄了气。正确的心态应该是：认识到失败是在所难免的，每次没有完成对自己的承诺时，对自己说："我离习惯的养成又进了一步"。习惯培养的过程就像闯关，打怪升级才能提升战力，如果前进的道路一马平川，到了终点如何有能力对抗大boss？要知道，习惯要能够禁得住任何大的小的考验，才能被刻在骨子里，受益终身。
* Saturday, 25 January 2020
** 09:18 晨间记录
*** 天气/温度/地点：多云/4°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨晚跨年，看《灵魂摆渡.黄泉》，1点多入睡。
*** 当前在培养的习惯是？跑步
*** 我的人生目标是什么？（长期短期，不同方面）
    长期目标：有能力随时带父母环游世界；工作上有自己的作品；个人自律。
    短期目标：考上研究生
*** 今天打算怎么安排？（上午，下午，晚上）
    大年初一，随缘吧～
** 22:45 晚间总结
*** 今天做了些什么？
    大年初一，早上起来电话拜年，然后一天看完了《我们与恶的距离》，太好看了！
*** 今天有什么值得夸奖自己的地方？（鼓励）
    《我们与恶的距离》一部很深刻的剧集。
*** 今天有什么待改进的地方？（反思）
    因为不想错过《我们与恶的距离》，没有跑步。其实这个问题是可以解决的，让老妈先看其他的剧，等我跑完步再一起看就好了。
*** 还有什么想说的？(感悟)
    看完了《我们与恶的距离》，HBO出品，很棒的一部剧。面对失去亲人，人会被巨大的悲痛裹挟，不能原谅施害人的家属也情有可原。但这种悲痛不应当被媒体当作炒作的筹码，也不应当以此为由践踏人权，甚至迫害施害人家属。即使罪犯也有辩护与上诉的权利，因为人人平等不是一句空话。我想那些维护司法公正的正义之士，无论是检察官或律师，都应当受到应有的尊重。
* Friday, 24 January 2020
** 08:39 晨间记录
*** 天气/温度/地点：雨/6°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    睡前刷了一会儿手机，看了一篇关于自律与习惯培养的文章，明白了自律是一个漫长且煎熬的过程。而那些自律的人，只不过养成了一个又一个的好习惯，慢慢累加，慢慢累加，才最终成就了「骨子里」的自律的。

晚上11:30左右睡觉。做了一个很清晰的梦：为了考研究生，我去重读高中，遇到了许多以前的同学。陌生的教室，熟悉的同学。我问长伟他为什么要重读，他说为了提高理论的深度，为工作铺垫。我是为了考研究生，其他同学是为了上大学。故事虽然毫无逻辑，但能够说明我的一些心绪。

一个人在负重前行的路上，遇到了能一起前进的伙伴，那种惊喜感不言而喻。
*** 当前在培养的习惯是？每天跑步。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期目标：随时有能力带父母环游世界；专业能力卓著；更自律，更优秀。
    短期目标：考上研究生
*** 今天打算怎么安排？（上午，下午，晚上）
    今天最重要的一件事情，初步实现org agenda。
** 10:12 org-agenda设计续
   需要思考的几个问题：
   * 项目如何处理？
   * 需要的几个清单？
     日程表(有时间戳)，收集箱，下一步行动（next），将来/也许，等待（waitting），项目。
   * 需要那些情境？
     情境用标签表示：@outside @review（阅读回顾清单） @phone

GTD的概念和org agenda概念对应
 * 收集箱：#+CATEGORY:Inbox
 * 下一步行动：NEXT关键词
 * 将来/也许：#+CATEGORY:Someday/Maybe
 * 等待清单：WAITTING关键字
 * 项目：@Project
 * 普通任务：TODO

重要的不是GTD的概念与org agenda概念的对应是否合理，重要的是写elisp函数封装处理的细节。
本质上，任务在三块区域迁移：收集箱（未处理），将来/也许清单（预处理），目前要做的工作（即将执行）。
所以建立三个文件：inbox.org（待处理的提示信息），someday.org（将来做的任务和未激活的项目），newgtd.org(单独的任务和已确定下一步行动的活跃项目)

我的几种情境分类：
 * 阅读、回顾相关文章资料 @review
 * 打电话处理相关事务 @phone
 * 思考、研究一些问题并查阅资料 @research

我的几个TODO状态关键词：TODO，NEXT，APPT，WAITTING，DONE，CANCELLED

** 23:30 晚间总结
*** 今天做了些什么？
    睡觉，跑步，看春晚，晚上看了部分《灵魂摆渡.黄泉》
*** 今天有什么值得夸奖自己的地方？（鼓励）
    跑步没有落下
*** 今天有什么待改进的地方？（反思）
    无
*** 还有什么想说的？(感悟)
    时间晚了，新年快乐！等到食谱买到了。学习做饭，来年大年三十，我要做一桌好菜。
* Thursday, 23 January 2020
** 10:03 晨间记录
*** 天气/温度/地点：多云 /7°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨晚不太好，状况不佳，却要强行ZW。还玩了会儿王者，2点多才睡觉。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期目标：随时有能力带父母环游世界；工作上有自己的作品；个人自律，分享经验。
    
    短期目标：考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    无论一天早晨几点起床，状态怎样，都不应该影响GTD。
** 12:09 org agenda设计
   需要思考的几个问题：
   * 项目如何处理？
   * 需要的几个清单？
     日程表(有时间戳)，收集箱，下一步行动（next），将来/也许，等待（waitting），项目。
   * 需要那些情境？
     情境用标签表示：@outside @review @phone

GTD的概念和org agenda概念对应。

清单——#+CATEGORY:
 * 收集箱：#+CATEGORY:Inbox
 * 下一步行动：NEXT关键词
 * 将来/也许：#+CATEGORY:Someday/Maybe
......
** 21:40 晚间总结
*** 今天做了些什么？
    上午10点多起床，中午看了会儿电视，下午睡一觉，晚上和老妈看韩剧《当你沉睡时》。
*** 今天有什么值得夸奖自己的地方？（鼓励）
    无
*** 今天有什么待改进的地方？（反思）
    要反思的不是今天有什么做的不好的地方，要反思的是这种时时像地方敌人一样地方自己的心态。没有人规定每天都得学习，没有都得收获满满，每天都得有满足感。今天本来就没有承诺必须要做什么，为什么要有这种负罪感，无端增加脑袋中的负担？不对，我明白了，这种不好的感觉来自没有跑步。每天跑步是我给自己的承诺！我的意志力已经连在跑步机上跑步都不能坚持了吗？这是需要反思的！

鉴于如今的体重，跑步一天都不能落下，而且得加量，每天跑两次。
*** 还有什么想说的？(感悟)
    在什么样子的环境里面做什么事情。在书房就要学习，在卧室就要睡觉。

    买的一箱精酿啤酒，喝了三瓶。说实话，我有点失望，和普通的工啤味道别无二致。
* Wednesday, 22 January 2020
** 08:46 晨间记录
*** 天气/温度/地点：多云/6°/上河老家
*** 早上好，昨晚睡得怎么样？
    睡前读了18分钟《傅雷家书》。12点左右睡觉，5点左右醒来上厕所，到客厅里继续睡。早上多次被闹钟打断，明显感觉睡眠质量不是很好。我得重新思考睡眠质量与闹钟设定的关系了。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期目标：随时有能力带父母环游世界；工作上有自己的作品；个人通过自律改变自己，影响他人。

    短期目标：考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    上午贴对年，整理要带走的物品。下午晚上随缘吧，把org agenda放在心上。
** 21:46 晚间总结
*** 今天做了些什么？
    上午贴了对联，整理了要带走的物品。下午和爸妈上街，晚上理了发，看《灵魂摆渡》。跑步20min，2.5km。
*** 今天有什么值得夸奖自己的地方？（鼓励）
    收拾东西前运用了《搞定》里的方法：核查清单。
*** 今天有什么待改进的地方？（反思）
    体重越来越不正常了，得加大跑步的量了。
*** 还有什么想说的？(感悟)
    唯有学习与学习后的成就感能够治疗我的空虚。
* Tuesday, 21 January 2020
** 07:18 晨间记录
*** 天气/温度/地点：晴/0°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    睡前看了一会儿《傅雷家书》，看到傅雷夫妇对儿子无微不至的关心，尤其是恋爱方面提点甚多。父母说话的语气是严肃的，但我读着读着却笑了出来。他们为儿子忧虑时的小抱怨有些可爱呢。哈哈哈。
然后12点左右睡觉，1点多醒来一次。
*** 我的人生目标是什么？（长期短期，不同方面）
长期目标：有能力随时带父母环游世界；工作上有自己骄傲的作品；个人自律，多阅读，多分享，更优秀。

短期目标：考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
今天要去外婆家吃饭，所以我学习的时间不固定。大概就是带一本《傅雷家书》和电脑。最重要的任务还是使用org mode重新实现GTD。
** 16:51 disqus评论懒加载代码

   #+BEGIN_SRC html
   <div id=\"disqus_thread\"></div>
   <script>
    function loadDisqus() {
      // Disqus 安装代码
      var d = document, s = d.createElement('script');
      s.src = 'https://geekinney-blog.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    }

    // 通过检查 window 对象确认是否在浏览器中运行
    var runningOnBrowser = typeof window !== \"undefined\";
   // 通过检查 scroll 事件 API 和 User-Agent 来匹配爬虫
   var isBot = runningOnBrowser && !(\"onscroll\" in window) || typeof navigator !== \"undefined\" && /(gle|ing|ro|msn)bot|crawl|spider|yand|duckgo/i.test(navigator.userAgent);
   // 检查当前浏览器是否支持 IntersectionObserver API
   var supportsIntersectionObserver = runningOnBrowser && \"IntersectionObserver\" in window;

    // 一个小 hack，将耗时任务包裹在 setTimeout(() => { }, 1) 中，可以推迟到 Event Loop 的任务队列中、等待主调用栈清空后才执行，在绝大部分浏览器中都有效
    // 其实这个 hack 本来是用于优化骨架屏显示的。一些浏览器总是等 JavaScript 执行完了才开始页面渲染，导致骨架屏起不到降低 FCP 的优化效果，所以通过 hack 将耗时函数放到骨架屏渲染完成后再进行。
    setTimeout(function () {
      if (!isBot && supportsIntersectionObserver) {
	// 当前环境不是爬虫、并且浏览器兼容 IntersectionObserver API
	var disqus_observer = new IntersectionObserver(function(entries) {
	  // 当前视窗中已出现 Disqus 评论框所在位置
	  if (entries[0].isIntersecting) {
	    // 加载 Disqus
	    loadDisqus();
	    // 停止当前的 Observer
	    disqus_observer.disconnect();
	  }
	}, { threshold: [0] });
	// 设置让 Observer 观察 #disqus_thread 元素
	disqus_observer.observe(document.getElementById('disqus_thread'));
      } else {
	// 当前环境是爬虫、或当前浏览器其不兼容 IntersectionObserver API
	// 直接加载 Disqus
	loadDisqus();
      }
    }, 1);
   </script>
   #+END_SRC
** 21:35 晚间总结
*** 今天做了些什么？
早上7点多醒来在床上看了一个小时的《傅雷家书》，然后和爸妈回老家。中午在外奶家吃了饭，下午睡了一觉。尝试了一些新的博客评论系统，最终成功使用valine替换disqus。valine可以在国内访问，还比较满意。晚上陪老妈看了几集灵魂摆渡2。
*** 今天有什么值得夸奖自己的地方？（鼓励）
读傅雷的家书教会了我调节情绪。

上午被老爸说了几句，有点生气。心里默默难受的时候想到了傅雷在家书中写到的，自己年轻时的脾气常常使儿子难受，夫人受折磨，所以儿子（傅聪）不在身边时反思自己，常常觉得愧疚。是呀，本来就是一些小事。父子交谈，有时意见不合，有时多啰嗦了几句，本就都是好意。犯不着为了这些使自己心情糟糕，又折磨了身边的人。想着想着，心情便舒展了许多。
*** 今天有什么待改进的地方？（反思）
爸妈说的话应当放在心上。我会下意识的忽略爸妈的叮嘱，以致于像晾衣服，叫人这些小事总需要他们唠叨。究其原因，我认为这些本就是无关紧要的事情。但是，最好不要让爸妈总是因为这些小事操心。即使是胸怀天下的人内心也当有一份细腻与柔情，不是吗？
*** 还有什么想说的？(感悟)
    喜欢《灵魂摆渡2》的「旧事」那两集，一开始没看懂，随着剧情的发展慢慢的感受到编剧想要表达的战乱时期人民的疾苦。像灵魂摆渡人这样历经千年时代变革，看尽人世沧桑的存在最懂人情能暖，也最能触动观众内心最柔软的部分。

听了大内最新一期节目，晓辉和相征聊汪曾祺。汪老爷子是个真实可爱的人，我很喜欢他的文风，有空定要好好读读他的作品。
* Monday, 20 January 2020
** 08:07 晨间记录
*** 天气/温度/地点：雾/0°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨晚睡前在京东上买了精酿啤酒，价格130多。听大内一直对精酿啤酒很好奇，这次恰逢春节，终于有机会品尝一下了。
    12:30熄灯睡觉，估计要到1:00多才睡着。6点和7点分别醒来了一次，小眯了一会就到了8点。又记不清梦见什么了。我应该在早晨记忆尚存的时候做些记录。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期目标：有能力和时间带父母环游世界；工作上有引以为傲的作品；个人方面更自律，多读书，更优秀。
    短期目标：考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    吃完早饭，到超市买东西（读书笔记相关，口罩...），然后今天的主要工作也是总结完《搞定》，调整org-agenda。顺带读一读《傅雷家书》。
    * [X] 买东西
    * [X] 总结搞定
    * [X] 阅读《傅雷家书》

** 21:31 晚间总结
*** 几句话总结一下今天？
    早上在小吃铺吃了馄饨和烧卖，然后去万达的超市逛了逛，买了部分做读书笔记的文具。中午睡了会，下午总结搞定，折腾了blog。晚上读了会《傅雷家书》。
*** 今天有什么值得夸奖自己的地方？（鼓励）
    明白了一个道理：这个世界上令我好奇的事物，我想学习的知识，我想阅读的书籍浩如烟海，穷尽一生我也不能全部了解，学习，读完。从这个意义上看，生命短暂，时间宝贵，且行且珍惜。

开心的是通过《但是还有书籍》这部纪录片，让我认识了B站的up主小隐，从而让我意识到b站有很丰富的资源，很多有意思的up主的视频，很多前人的经验。它就像一个知识宝库，你的好奇心越大，探索欲越强烈，它带给你的智慧也越多。感谢，感恩有这样优秀的平台。也很幸运我认识到了这个道理。
*** 今天有什么待改进的地方？（反思）
    关于ZW这件事情，我一直没有认真的讨论过它。好吧，我实在是说服不了自己，的确的全方面的好好了解一下它。目前姑且制定一个习惯周期，这是比较合理的。把这个习惯记录进blog，表明我对它的重视。

关于中午午休。首要问题是午休前刷手机过了午休时间，进而影响下午的学习安排；其次是午休时间到了仍然瞌睡，不能果断起床。主要就是这两个问题。
之前一直想培养在床上不玩手机的习惯，多次失败后没有坚持下来，便不了了之了。现在我想将这个习惯的培养提上日程了。它会是解决午休第一个问题的灵丹妙药。至于第二个问题，根源在睡眠质量不高。所以平时要多锻炼，少ZW。减少从醒来的状态切换到学习的状态的时间也是很好的解决办法。这就需要改变午休的方式，比如在书房睡觉。先待定吧，着重把第一个问题解决好。

关于文字表达。写上面这段文字让我意识到自己缺乏书面表达的训练。如果我不动脑子的书写，文字中便充满了语病。如果我有意识的注重书写时的逻辑表达和用词，语句便会通顺许多。所以以后切忌“意识流式”写作，多留意表达通顺，多训练表达的美感。

还有一些，明天接着反思。

*** 还有什么想说的？（感悟）
    我不必为没有履行对自己的承诺而烦心，既然时间已经过去，何不乐观的去反思。每天不能只有反思，也要学会找到自己做得好的地方，懂得感恩。我把人的精神状态比作一个天秤，左边是鼓励，右边是反思。任何一边偏重都会导致天秤失衡。

读《傅雷家书》，在傅雷给儿子傅聪的信中，我可以真切的感受到傅雷对儿子生活方方面面的关心，这些内容关于俄文学习，关于乐理学习，关于处理恋爱与艺术的关系，关于儿子的心情....也有对自己的反思，傅雷的脾气有的时候会让儿子、妻子忧心。不行了，我得多读别人的文字，写的太不流畅了！
* Sunday, 19 January 2020
** 09:49 晨间日记
*** 天气/温度/地点：晴/4°/淮安御景城
*** 早上好，昨晚睡得怎么样？
    昨天12:40多睡觉，记不清梦见了什么。
*** 我的人生目标是什么？（长期短期，不同方面）
    长期愿景：有能力随时带父母环游世界；计算机行业里作出自己的成绩；个人方面养成自律的习惯并能影响他人。目前的目标是考上研究生。
*** 今天打算怎么安排？（上午，下午，晚上）
    今天做重要的事情是搞定org agenda。

*** 几句话总结一下今天？
    上午整理《搞定》笔记，中午吃了蛋炒饭，看完了《但是还有书籍》，了解了B站的up主小隐。下午睡了一觉，跑步30min，3.5km。晚上折腾blog，将org-journal导出到blog。晚上洗了澡，回来买了份“章福元”吃。
*** 今天最大的收获是什么？（鼓励）
    看了小隐一期关于做读书笔记的视频，了解了读书的仪式感：布置一个优雅的环境，用一些小道具，冲一杯热咖啡...
*** 有什么有待改进的地方？（反思）
    我感觉自己又陷入了那个怪圈：一旦一开始没有做好，接下来就会全盘皆输。早上没有按照预期的时间起床，接下来一天的时间就荒废了。这是一种很不好的做法。破局的办法是培养一些好的习惯，像晨间日记一样。习惯就是那些即使一天的状况再再糟糕，也要能雷打不动去做事情。培养了这些好的习惯（无论是长期的还是短期的），起码能保证自己的心情不那么糟糕。

    举几个例子：不知道要做什么的时候，看书！早上起来出去慢跑个几公里（前提是起早点）！傍晚按时跑步！中午不要在床上睡觉！
    另一个方面，我得认识到这几天糟糕的情绪与状态的根源：没有兑现自己的承诺。每天我都在晨间日记里面写下今天要做的事情，但是当自己没有履行承诺时，便会产生消极情绪。这种消极情绪持续积累便让人忘了GTD。所有以后我每天只列出一件最重要的事情，其余的培养成习惯，剩下的做一步看一步。我不知道这么做是否合理，但对我来说是有效的。
** 15:00 看完《但是还有书籍》有感
   看完《但是还有书籍》和小隐的一期视频后，我有一种深深的焦虑感。焦虑于我没能在自己前20年的人生里与阅读为伴，没能在阅读的世界里开拓眼界，汲取知识，培养素养，学会表达。如果我能像小隐一样5岁便能在书籍的海洋中遨游，在知识的圣殿里流连忘返，此刻的我一定不会是此刻的我。我的心境，我的思考方式，对待生活的态度，我的人生观、价值观都会有很大的不同。这个世界没有如果，幸好我遇见阅读还不算太晚。

始终让我意难平的是小隐的手账视频介绍自己在英国游学的经历。这种带着朝圣的心境在他国参观，享受自然最纯粹的洗涤，异国他乡的求学的心境与情结在我的脑海中挥之不去。我向往这样的生活。可能，当我到了那个环境时就没了此番的憧憬，但此刻的心情实在是令人难以平复。总结就是在面对优秀的人时，内心会产生愧疚感。对平时自己浪费了很多的时间而后悔。
