#+TITLE: 故事：材质、结构、风格和银幕剧作的原理
#+DATE: 2019-11-12
#+STARTUP: content
#+OPTIONS: toc:t H:3 num:3


*《故事：材质、结构、风格和银幕剧作的原理》/ [美] Robert Mckee / 周铁东 译 / 开始阅读：Nov 10, 2019*

* 序言
  ○ 《故事》讲述的是原理，而不是规则。规则说：“你必须以这种方式做。”原理说：”这种方式有效......而且经过了时间的验证。”两者有着本质的区别。

  ○ 《故事》讲诉的是永恒的、普遍的形式，而不是公式。

  ○ 《故事》讲诉的原始模型，而不是陈规俗套。原始模型故事挖掘出一种普遍性的人生体验，然后以独一无二、独具文化特异性的表现手法对它进行装饰。陈规俗套则将这一形式颠倒过来：其内容和形式的匮乏势所难免。它将自己局限于一种狭隘的、具有文化特性的体验之中，然后饰之以陈腐而无特色的庸常形式。

  ○ 《故事》的论述是一丝不苟的，而不是旁门捷径。尽管粗制滥造者能够以其打字速度迅速填满纸稿，但优秀的电影剧作家却总是惜字如金，不断删改，力图以最少的文字表达最多的信息。

  ○ 帕斯卡尔曾给朋友写过一封长而无当的书信，然后在信尾的又及中深表歉意，说他没有时间写一封短信。就像帕斯卡尔一样，剧作家们明白简约是关键，简明扼要需要花费时间，而卓越超群来自孜孜以求。

  ○ 《故事》论述的是写作的现实，而不是写作的秘诀。艺术的真谛并不是要策划什么阴谋来保守秘密。如果银幕剧作家未能以存粹的戏剧化场景打动我们，他就不能想小说家利用作者的声音或想戏剧作家利用独白一样，隐藏在自己的语言背后。

  ○ 《故事》论述的是如何精通这门艺术，而不是如何揣摩市场行情。

  ○ 《故事》论述的是对观众的尊重，而不是对观众的鄙薄。

  ○ 天才作家写不出好作品大抵有两个原因：要么是被一个他们觉得非证明不可的观念蒙蔽了双眼，要么是被一种他们必须表达的情感所驱策。而天才作家写出好作品一般是因为这个原因：他们被一种要打动观众的欲望所感动。

  ○ 《故事》论述的是独创，而不是复制。

* PART I 作家和故事艺术
** 故事问题
*** 故事的衰竭
    ○ 日复一日，我们寻求亚里士多德在《伦理学》中提出的那一古老问题的答案：一个人应该如何度过他的一生？但问题的答案总是在规避着我们。当我们力图使我们的手段合乎我们的梦想时，当我们试图将我们的思想融入我们的激情时，当我们力图让我们的欲望变成现实时，那一问题的答案始终躲藏在飞速流转，难以捉摸的时间后面。我们犹如乘坐一艘飞船
