#+TITLE: 搞定I：无压生活的艺术
#+DATE: 2019-10-20
#+STARTUP: content
#+OPTIONS: toc:nil H:2 num:2
#+TOC: headlines:2

* 收集阶段：归拢材料
  捕获工作和生活中的所有未竟之事，这个阶段通常要花费1~6个小时。很多事情不是那么重要或紧急，但是它们会控制你，无谓消耗你的大量精力，始终让你觉得“还有什么事情要办”。所以收集的过程必须事无巨细。
  * 收集过程中的要点
    * 收集时养成标注时间的习惯
    * 收集的过程不做细枝末节的整理
    * 收集过程中遇到已经列在任务清单的事情，照样收集
    * 遇到紧急需要处理或不想忘记的事情，可以立即处理就处理掉，否则做上标记。
    * 建立自己的“未竟事宜的引子”的清单
    * 收集的内容要定期清理
* 理清阶段：清空工作篮
  * 处理原则
    * 首先处理最上面的事务
    * 一次一事
    * 永远不要把事务再次放回工作篮
  * 处理流程
    * 需要付诸行动则确定“下一步行动”是什么
    * 如果不需要付诸行动，分为三类：垃圾、待酝酿的事务、参考资料
      * 垃圾扔掉
      * 待酝酿的事务：加入“将来/也许”清单；或写入日程表，备忘录
      * 参考资料加入归档系统
    * 确定了“下一步行动”后面临三种选择：
      * 立刻执行（两分钟内可完成）
      * 委派他人（自己不是完成任务的最佳人选）
      * 推迟执行，有待进一步组织
    * 开阔视野，确定项目

* 组织整理：建立好清单
  *基本分类*

    * “项目”清单
    * 项目的辅助资料
    * 记录在日程表中的行动和信息
    * “下一步行动”清单
    * “等待”清单
    * 参考资料
    * “将来/也许”清单

保持不同类别间界线明确，至关重要。组织整理需要的仅仅是“清单”和“文件夹”。

 *组织整理行动提示信息*

   日程表应该只记录对时间有刚性需求的行动\\
   剩下的就是对时间没有苛刻要求的ASAP行动。
   * 根据情境分类
     情境就是完成行动所需要的工具、地点或情形。将同一情境下的行动统一执行可以大大提高效率。
     常见的一些情境分类例子：电话；在电脑旁；外出事宜；在办公室时；在家时；议事日程；阅读/回顾...
   * “等待”清单
     那些等待别人完成的任务需要清单来跟踪。”等待”清单上的内容是那些你不关心过程只关心结果的。

 *组织整理项目提示信息*

 项目是那些需要多个步骤才能完成的事情。项目清单不应该包含执行的具体细节或方案，也不应该按照重要性、大小、紧急程度来排序。事实上，我们每天不需要理睬“项目”清单，而应将更多的精力放在日程表、行动清单和突发事件上。既然这样，维护“项目”清单的意义是什么呢？项目让我们对自己要做的事情有宏观上的掌控感以及对工作量有一个客观的认识，这在很大程度上减缓了大脑的负担。

 如何寻找待发现项目？

 * 当前活动：从目前的日程表、行动清单和工作区中需要事件之间的关联性
 * 较高视野的兴趣和项目：从职责、目标、愿景及核心价值观这些更长远、更重要的角度思考会发现一些“探究”性质的项目。这些项目一旦得到确认，会让人产生一种掌控自己世界的满足感
 * 当前的问题和机会：分为三类，当前存在的项目问题，流程改进，创意和能力建设

   项目细分：

   * 个人/职业
   * 委派给他人的项目
   * 特定类型的项目

  对项目分类是为了保证一目了然的回顾，对项目做到心中有数。不要将“项目的辅助信息”作为提示信息。关于项目的想法或念头应该被保存起来，作为项目的辅助信息。


 *组织整理非行动性资料*

 不要将可执行的行动和不可执行的事务混杂在一起，这样会严重影响个人管理系统的运行。和可执行的行动一样，这些非行动的资料也应该被妥善的保存。

 非行动性资料非为三类：参考资料；“将来/也许”类行动的提示信息；不需要的东西。
 
 参考资料需要建立个人的资料归档系统。

 “将来/也许”清单保存目前不需要行动的提示信息。它可能源于你创造性的想象力，记录那些当你有了时间、金钱和机会，你希望做的事情；它让你重新评估当前进行中的项目，将没有进展的项目放回“将来/也许”清单；也可能是你感兴趣的一些类别，如想读的一些书、想看的一些电影、周末的外出旅行以及五花八门的想法...

 *核查清单*
 
 核查清单的目的是帮助我们关注项目，工作流程和程序、事件、爱好、职责等领域中可能出现的潜在问题。这里有一些例子帮助读者理解：
   * 旅行核查清单
   * 每周回顾
   * 要保持联系的人
   * 工作职责范围
* 回顾阶段：保障系统的有效运行
  回顾的主要目的是保证系统实时更新，紧跟事态发展，这样在行动的时候才能作出恰当的选择。明白了为什么要回顾，接下来需要考虑两个问题。

  *要回顾那部分内容？在什么时候进行？*

  

  
