#+TITLE: 关于戈楷旎
#+STARTUP: showall
#+OPTIONS: toc:nil H:2 num:0 title:nil

=戈楷旎= 就是我的英文名 /Geekinney/ 的谐音～

* 关于我和EMACS
emacser，本科计算机专业毕业。喜爱读书和唱歌，喜爱折腾和hack emacs。我的一天90%的时间是在[[https://www.gnu.org/software/emacs/][emacs]]中的度过的。我在emacs中编程、写作、学习、管理日程...，我的博客中相当一部分内容是与emacs相关的。关于什么是emacs，可以看懒猫的这两篇文章：[[https://manateelazycat.github.io/emacs/2016/03/06/what-is-emacs.html][Emacs是一种生活方式]] 和 [[https://manateelazycat.github.io/emacs/2018/12/11/study-emacs.html][如何学习emacs]]。

如果你是程序员，我强烈推荐你使用emacs，它会极大的提高你的学习工作效率。如果你不是程序员，但是爱折腾，我也推荐你尝试emacs，它会成为你时间管理与文档书写的利器。

emacs入门，可以观看子龙山人的[[https://v.youku.com/v_show/id_XMTUwNjU0MjE0OA==.html][Master Emacs in 21 Days]]系列视频。使用emacs过程遇到问题可以在[[https://emacs-china.org][emacs-china]]论坛向大神求助。At last, happy hacking emacs!

* 为什么开设博客
计算机专业出身，对于 *技术从理论到实践的想象* 从未停止，于是想用学过的技术做点实用的事情。一直有拥有独立博客的想法，正好毕设又学习了Django框架，便开始折腾起来。2019年暑假博客初步建成，使用Django+mysql，后面又改为静态博客，经过了多次改动，最后纯粹使用 /Emacs orgMode/ 。过程详细记录在[[https://blog.geekinney.com/post/experience-of-setting-up-my-own-blog-site.html][记我的博客折腾经历]]这篇文章中。

除了实现对技术的想象，搭建博客更多的是想 *记录自己的成长* 。交流、学习、工作、电影、播客、动漫、文章....我们接触生活的每一种方式都会在脑海中留下大量信息。这些信息进行提炼、联系、再创造就产生了灵感和思考。某些深刻的思考成了我们的生活经验，潜移默化的指导生活；一般的思考留在了我们的记忆中，等待被诉诸文字或言语的机会；而大多数的灵感则在片刻停留后，销声匿迹。我的博客要记录那些 *于生活有益的经验，于工作有助的思考，于无声处作用的灵感* ，这些便是成长的印记。

* 关于版权的说明
若无特别说明，文章皆为原创，图片来自pixabay, unsplash等正版图像素材库。

本站的所有内容均遵循“署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)”协议，这意味着你可以在标记出处的情况下自由的分享或进行二次创作。关于此协议的详细内容请看[[https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh][这里]]。

* 关于隐私与评论
博客不会追踪单个访客行为，且不要求访客提供敏感信息（比如真实姓名，身份证号码等），因而不会有任何隐私泄漏问题。

欢迎评论留言，但请遵守基本的礼貌规范，禁止发布任何有关淫秽，反动，暴力，赌博，恐吓或违法的评论，在尊重言论自由的同时保持和平与理性。请勿对其中的任何评论者采取不友好的评论与过激争吵行为。对此我将保留删除评论的权利。

* 交流联系
  如对博客内容有更多问题，欢迎交流探讨：
  * /Email: kinneyzhang666@gmail.com/
  * /Github: https://github.com/Kinneyzhang/

* 友情链接
 * [[https://hiwannz.com][见字如面]] (生活.职场)
 * [[https://www.91the.top][IT玩客]] (技术)
 * [[https://www.boatsky.com][太空船博客]] (前端.书评.影评)
 * [[https://mikukonai.com][Project Aurora]] (综合)
 * [[https://diygod.me][Hi, DIYgod]] (综合)
 * [[https://www.huhexian.com][青山绿水]] (生活)

